version: '3'

services:
  simple-task-executor:
    build: . 
    container_name: simple-task-executor
    ports:
     - "5000:80"
    environment:
      - PARTNER_VOLUME_PATH=/opt/data/partner-volume/
    volumes:
      - /home/chris/Desktop/executor/partner-volume:/opt/data/partner-volume
